# Generated by Django 4.2.7 on 2025-12-19 15:51

from django.db import migrations, models
import django.db.models.deletion
import tenants.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_tenant_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FEE', 'Fee'), ('PENALTY', 'Penalty')], default='FEE', max_length=20)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring')], default='ONE_TIME', max_length=20)),
                ('basis', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage'), ('SLAB', 'Slab Based')], default='FIXED', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0, help_text='Value or %', max_digits=10)),
                ('slab_config', models.JSONField(blank=True, default=dict, help_text="{'1-30 days': 2%, '31-60 days': 4%}")),
                ('recovery_stage', models.CharField(choices=[('DISBURSEMENT', 'Deduct from Disbursement'), ('ONGOING', 'Ongoing'), ('MISSED_EMI', 'Missed EMI'), ('POST_DEFAULT', 'Post Default')], default='DISBURSEMENT', max_length=50)),
                ('recovery_mode', models.CharField(choices=[('AUTO', 'Auto (Next Bill)'), ('MANUAL', 'Manual Collection')], default='AUTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_charge_configs',
            },
        ),
        migrations.CreateModel(
            name='InterestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('interest_type', models.CharField(choices=[('FIXED', 'Fixed Rate'), ('FLOATING', 'Floating Rate')], default='FIXED', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Annual Rate %', max_digits=5)),
                ('benchmark_type', models.CharField(blank=True, choices=[('REPO', 'RBI Repo Rate'), ('MCLR', 'Bank MCLR'), ('TBILL', 'T-Bill Rate')], max_length=20, null=True)),
                ('spread_margin', models.DecimalField(decimal_places=2, default=0.0, help_text='Mark Up', max_digits=5)),
                ('accrual_method', models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPOUND', 'Compound')], default='SIMPLE', max_length=20)),
                ('accrual_stage', models.CharField(choices=[('PRE_EMI', 'Pre-EMI'), ('POST_EMI', 'Post-EMI')], default='POST_EMI', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_interest_configs',
            },
        ),
        migrations.CreateModel(
            name='RepaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule_type', models.CharField(choices=[('EMI', 'EMI'), ('BULLET', 'Bullet'), ('STEP_UP', 'Step-up')], default='EMI', max_length=50)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI_WEEKLY', 'Bi-weekly'), ('WEEKLY', 'Weekly')], default='MONTHLY', max_length=50)),
                ('cycle_date', models.IntegerField(default=5, help_text='Day of month (e.g., 5th)')),
                ('waterfall_sequence', models.JSONField(default=tenants.models.default_waterfall, help_text='Order of appropriation')),
                ('grace_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_configs', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_repayment_configs',
            },
        ),
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_age', models.IntegerField(default=21)),
                ('max_age', models.IntegerField(default=60)),
                ('allowed_income_types', models.JSONField(default=list, help_text="['Salaried', 'Self-Employed']")),
                ('min_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_foir', models.DecimalField(decimal_places=2, default=60.0, help_text='Max FOIR %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_rules', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_risk_rules',
            },
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('SALARIED', 'Employees'), ('PROFESSIONAL', 'Professionals'), ('BUSINESS', 'Business')], default='SALARIED', max_length=50)),
                ('rules_config', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_scorecards',
            },
        ),
        migrations.CreateModel(
            name='TenantLoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('loan_type', models.CharField(choices=[('Payday Loan (Short-term Loan)', 'Payday Loan (Short-term Loan)'), ('Personal Loan (Unsecured)', 'Personal Loan (Unsecured)'), ('Business Loan', 'Business Loan'), ('Group Loan (JLG/SHG Model)', 'Group Loan (JLG/SHG Model)'), ('Unsecured Education Loan', 'Unsecured Education Loan'), ('Consumer Durable Loan', 'Consumer Durable Loan'), ('Loan Against Property (LAP)', 'Loan Against Property (LAP)'), ('Loan Against Shares/Securities', 'Loan Against Shares/Securities'), ('Gold Loan', 'Gold Loan'), ('Vehicle Loan', 'Vehicle Loan'), ('Secured Education Loan', 'Secured Education Loan'), ('Supply Chain Finance', 'Supply Chain Finance'), ('Bill/Invoice Discounting', 'Bill/Invoice Discounting'), ('Virtual Card (Buy Now, Pay Later)', 'Virtual Card (Buy Now, Pay Later)'), ('Credit Line - OD Facility', 'Credit Line - OD Facility'), ('Agriculture Loan', 'Agriculture Loan'), ('Microfinance Loan', 'Microfinance Loan'), ('Equipment Financing', 'Equipment Financing'), ('Working Capital Loan', 'Working Capital Loan'), ('Medical Emergency Loan', 'Medical Emergency Loan')], max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_tenure', models.IntegerField()),
                ('max_tenure', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charges', models.ManyToManyField(blank=True, to='tenants.chargeconfig')),
                ('interest_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.interestconfig')),
                ('repayment_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.repaymentconfig')),
                ('risk_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.riskrule')),
                ('scorecard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.scorecard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_products', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenant_loan_products',
            },
        ),
    ]
