# Generated by Django 4.2.7 on 2025-12-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_dashboard'),
        ('los', '0004_kycdetail_remove_guarantor_loan_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditassessment',
            old_name='approved_limit',
            new_name='approved_amount',
        ),
        migrations.RenameField(
            model_name='creditassessment',
            old_name='score',
            new_name='cibil_score',
        ),
        migrations.RenameField(
            model_name='loanapplication',
            old_name='amount',
            new_name='requested_amount',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='tenure_months',
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='approved_roi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditassessment',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='account_type',
            field=models.CharField(default='Savings', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='business_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='disbursement_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='dob',
            field=models.DateField(default='2000-01-01', help_text='Used for Age Knock-out Check'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='email',
            field=models.EmailField(default='example@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='employment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='first_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='foir_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='income_type',
            field=models.CharField(choices=[('Salaried', 'Salaried'), ('Self-Employed', 'Self-Employed')], default='Salaried', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_agreement_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_cibil_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_enach_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_geo_limit_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_penny_drop_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='is_video_kyc_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='last_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mandate_type',
            field=models.CharField(default='eNACH', max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mobile_no',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='net_cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='office_address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='office_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='office_pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='pan_number',
            field=models.CharField(default='ABCDE1234F', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adminpanel.loanproduct'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='requested_tenure',
            field=models.IntegerField(default=12, help_text='Tenure in Months'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='res_address_line1',
            field=models.CharField(default='Test Address', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='res_address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='res_city',
            field=models.CharField(default='Test City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='res_pincode',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='res_state',
            field=models.CharField(default='Test State', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kycdetail',
            name='document_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kycdetail',
            name='kyc_type',
            field=models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('VOTER_ID', 'Voter ID'), ('PASSPORT', 'Passport'), ('SELF_DECLARATION_VIDEO', 'Self Declaration Video'), ('SALARY_SLIP', 'Salary Slip'), ('BANK_STATEMENT', 'Bank Statement'), ('ITR', 'ITR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Application'), ('KNOCKOUT_PENDING', 'Knock-out Checks'), ('DOC_UPLOAD', 'Document Upload'), ('UNDERWRITING', 'Underwriting In-Progress'), ('HOLD', 'On Hold'), ('SANCTIONED', 'Sanctioned'), ('PRE_DISBURSEMENT', 'Pre-Disbursement Checks'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NEW', max_length=30),
        ),
    ]
