# Generated by Django 4.2.7 on 2025-12-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_2fa_enabled_user_two_fa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MASTER_ADMIN', 'Master Admin'), ('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'Staff'), ('LOAN_OFFICER', 'Loan Officer'), ('UNDERWRITER', 'Underwriter'), ('FINANCE_STAFF', 'Finance Staff'), ('SALES_EXECUTIVE', 'Sales Executive'), ('BORROWER', 'Borrower')], default='BORROWER', max_length=50),
        ),
    ]
